name: Release
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
      - name: Install ALSA dev
        run: |
          sudo apt-get update
          sudo apt-get install alsa libasound2-dev
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Install dependencies
        run: rm package-lock.json
        run: npm install
      - run: npm run build
      - name: Release
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
